name: Deploy Weather.API to Azure

on:
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'ea-app-assignment3-westeu'



jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Install dependencies
        run: dotnet restore ./Weather.API/Weather.API.csproj

      - name: Build
        run: dotnet build ./Weather.API/Weather.API.csproj --configuration Release --no-restore

      # publish
      - name: Publish
        run: dotnet publish ./Weather.API/Weather.API.csproj --configuration Release --output ./publish
      


      # deploy to azure webapp
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v1
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.API_PUBLISH_SECRET }}
          package: ./publish


  